// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArDU3mLEjPOvoJcxadnt-rz40efx212qM',
    appId: '1:304106357554:web:7a61fd98443170be078d2b',
    messagingSenderId: '304106357554',
    projectId: 'chaton-b16bb',
    authDomain: 'chaton-b16bb.firebaseapp.com',
    storageBucket: 'chaton-b16bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChPGIkZ0Ut65VNTQ-7oLNNdocvXZQ4VP8',
    appId: '1:304106357554:android:61167cc77aebe2dd078d2b',
    messagingSenderId: '304106357554',
    projectId: 'chaton-b16bb',
    storageBucket: 'chaton-b16bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC14R7WDqcYmQ3b4Jo8eNg1bV2LZlOwF_I',
    appId: '1:304106357554:ios:74fc456b57714587078d2b',
    messagingSenderId: '304106357554',
    projectId: 'chaton-b16bb',
    storageBucket: 'chaton-b16bb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC14R7WDqcYmQ3b4Jo8eNg1bV2LZlOwF_I',
    appId: '1:304106357554:ios:74fc456b57714587078d2b',
    messagingSenderId: '304106357554',
    projectId: 'chaton-b16bb',
    storageBucket: 'chaton-b16bb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArDU3mLEjPOvoJcxadnt-rz40efx212qM',
    appId: '1:304106357554:web:6af781da3bdc05b1078d2b',
    messagingSenderId: '304106357554',
    projectId: 'chaton-b16bb',
    authDomain: 'chaton-b16bb.firebaseapp.com',
    storageBucket: 'chaton-b16bb.appspot.com',
  );
}
